server:
  port: 8082

fiap:
  debug: true

spring:
  datasource:
    url: jdbc:h2:~/fiaprecrutamentodb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /database