server:
  port: 8082

fiap:
  debug: true
  secret: f14pS3cr37
  expireInSeconds: 300

spring:
  datasource:
    url: jdbc:h2:~/fiaprecrutamentodb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /database

